/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.IOException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String linterLog = linter("\\main\\resources\\manyErrors.js");
    }
   public static boolean hasSemicolon(String currentLine){
       if (currentLine.endsWith("{") || currentLine.endsWith("}") || currentLine.endsWith(";")){
           return true;
       }
       if (currentLine.contains("if") || currentLine.contains(
               "else") || currentLine.contains("//") || currentLine.equals(
               "")){
           return true;
       } else {
           return false;
       }

   }
    public static String linter(String newFileLocation){
        File newFile =
                new File(System.getProperty("user.dir") + "//src//" + newFileLocation);
        //create Scanner
        String typeErrors = "";
        try(Scanner myScanner = new Scanner(newFile)) {
            //set line number
            int location = 0;
            while (myScanner.hasNextLine()) {
                //if there are more lines, increment line location
                location++;
                //move to the next line
                String currentLine = myScanner.nextLine();
                //check conditions
                if(!hasSemicolon(currentLine)){
                    String error =
                            "Line " + location + ": missing semi-colon." + System.lineSeparator();
                    typeErrors += error;
                    System.out.println(error);
                }
            }
        } catch (IOException error){
            error.printStackTrace();
        }
        System.out.println(typeErrors.lines().count());
        return typeErrors;
    }
}

