/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void linterManyTest(){
        assertTrue(App.linter("main\\resources\\manyErrors.js").lines().count() > 10);
        assertEquals(App.linter("main\\resources\\empty-file.js").lines().count(),
                0);
        assertEquals(App.linter("main\\resources\\oneError.js").lines().count(), 1);
        assertEquals(App.linter("main\\resources\\someErrors.js").lines().count(),
                4);
        assertEquals(App.linter("main\\resources\\noErrors.js").lines().count(), 0);
    }
}
